version: "3"
services:

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "5000:11434"
    environment:
      OLLAMA_HOST: ollama
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    networks:
      - chat_go_net

  chatsupportagent:
    container_name: chatsupportagent
    build:
      context: ./target
      dockerfile: ./Dockerfile
    image: chatsupportagent:latest
    ports:
      - "8185:8185"
    environment:
      OLLAMA_HOST: ollama
      JAR_NAME: ChatSupportAgent-0.0.1-SNAPSHOT.jar
    restart: always
    networks:
      - chat_go_net

networks:
  chat_go_net:
    external: true
    driver: bridge