services:

  chatsupportagent:
    container_name: chatsupportagent
    build:
      context: ./target
      dockerfile: ./Dockerfile
    image: chatsupportagent:latest
    hostname: chatsupportagent
    ports:
      - "8185:8185"
    environment:
      JAR_NAME: ChatSupportAgent-0.0.1-SNAPSHOT.jar
      ENDPOINT: http://endpoint-kafka:8080/
      #http://endpoint-kafka:8080/ use esse formato do endpoint
    restart: always
    networks:
      - broker-kafka

networks:
  broker-kafka:
    external: true
    driver: bridge