version: "3"
services:

  chatsupportagent:
    container_name: chatsupportagent
    build:
      context: ./target
      dockerfile: ./Dockerfile
    image: chatsupportagent:latest
    ports:
      - "8185:8185"
    environment:
      JAR_NAME: ChatSupportAgent-0.0.1-SNAPSHOT.jar
      ENDPOINT_KAFKA: endpoint-kafka:8080
    restart: always
    networks:
      - broker-kafka

networks:
  broker-kafka:
    external: true
    driver: bridge