version: "3"
services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "5000:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    networks:
      - chat_go_net

  chat-support:
    container_name: chatsupportagent
    build:
      context: ./target
      dockerfile: ./Dockerfile
    image: chatsupportagent:latest
    ports:
      - "8185:8185"
    volumes:
      - .:/app
      - ./target/files:/files
    environment:
      environment:
      JAR_NAME: ChatSupportAgent-0.0.1-SNAPSHOT.jar
    networks:
      - chat_go_net

networks:
  chat_go_net:
    external: true
    driver: bridge