version: "3"
services:

  chatsupportagent:
    container_name: chatsupportagent
    build:
      context: ./target
      dockerfile: ./Dockerfile
    image: chatsupportagent:latest
    ports:
      - "8185:8185"
    environment:
      JAR_NAME: ChatSupportAgent-0.0.1-SNAPSHOT.jar
      FILE_PATH: /files
    restart: always
    networks:
      - chat_go_net


networks:
  chat_go_net:
    external: true
    driver: bridge